<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Canasta;
use App\Models\Ingrediente;
use Illuminate\Support\Facades\DB;

class CanastaIngredienteSeeder extends Seeder
{
    public function run(): void
    {
        $canastas = Canasta::all()->keyBy('nombre');
        $ingredientes = Ingrediente::all()->keyBy('nombre');

        $datos = [
            // Mediterránea
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Avena', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Leche', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Banana', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Frutos rojos', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Pepino', 'cantidad' => 220, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Tomate', 'cantidad' => 570, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Cebolla', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Aceitunas negras', 'cantidad' => 150, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Queso feta', 'cantidad' => 150, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Aceite de oliva', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Orégano', 'cantidad' => 18, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Filete de salmón', 'cantidad' => 350, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Quinoa', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Ajo', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Limón', 'cantidad' => 440, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Pasta integral', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Zucchini', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Pimientos', 'cantidad' => 550, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Lentejas cocidas', 'cantidad' => 570, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Laurel', 'cantidad' => 12, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Papa', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Berenjena', 'cantidad' => 700, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Pan integral', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Pollo', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Hummus', 'cantidad' => 220, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Zanahoria', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Garbanzos', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Aguacate', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Huevo', 'cantidad' => 720, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Arroz integral', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Yogur natural', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Yogur griego', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Miel', 'cantidad' => 250, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Nueces', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Manzana', 'cantidad' => 900, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Almendras', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Chía', 'cantidad' => 150, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Queso bajo en grasa', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Batata', 'cantidad' => 800, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Pescado', 'cantidad' => 350, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Pan de centeno', 'cantidad' => 440, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Albahaca', 'cantidad' => 20, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Piñones', 'cantidad' => 90, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Queso parmesano', 'cantidad' => 100, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Rúcula', 'cantidad' => 100, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Espinaca', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Vegetales mixtos', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Naranja', 'cantidad' => 1200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Mediterránea', 'ingrediente' => 'Mango', 'cantidad' => 530, 'unidad' => 'g'],

            // Vegana
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Aceite de oliva', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Aguacate', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Garbanzos', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Curry', 'cantidad' => 113, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Leche de coco', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Cebolla', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Ajo', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Tofu', 'cantidad' => 275, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Brócoli', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Arroz integral', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Frijoles negros', 'cantidad' => 270, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Pimientos', 'cantidad' => 550, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Tomate', 'cantidad' => 570, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Quinoa', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Hummus', 'cantidad' => 220, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Zucchini', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Berenjena', 'cantidad' => 700, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Láminas de lasaña', 'cantidad' => 250, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Bechamel vegana', 'cantidad' => 235, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Lentejas cocidas', 'cantidad' => 570, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Papa', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Zanahoria', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Salsa de soja', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Espinaca', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Masa para tarta', 'cantidad' => 230, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Arroz blanco', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Lechuga', 'cantidad' => 150, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Pasta integral', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Pan integral', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Frutos rojos', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Leche', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Banana', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Avena', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Almendras', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Semillas', 'cantidad' => 250, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Dátiles', 'cantidad' => 250, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Manzana', 'cantidad' => 900, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Naranja', 'cantidad' => 1200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Mango', 'cantidad' => 530, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Calabaza', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Albahaca', 'cantidad' => 20, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Nueces', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Chía', 'cantidad' => 150, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Granola', 'cantidad' => 275, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Proteína en polvo', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Mantequilla de maní', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Harina integral', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Yogur vegetal', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Tahini', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Pimentón', 'cantidad' => 45, 'unidad' => 'g'],
            ['canasta' => 'Canasta Vegana', 'ingrediente' => 'Chocolate amargo', 'cantidad' => 100, 'unidad' => 'g'],

            // Clásica
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Carne para milanesa', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Huevo', 'cantidad' => 720, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Pan rallado', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Lentejas cocidas', 'cantidad' => 570, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Papa', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Zanahoria', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Pimentón', 'cantidad' => 45, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Carne picada', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Puré de papas', 'cantidad' => 230, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Cebolla', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Espinaca', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Masa para tarta', 'cantidad' => 230, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Pollo', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Arroz blanco', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Pimientos', 'cantidad' => 550, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Pan integral', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Mermelada', 'cantidad' => 330, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Pasta', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Tomate', 'cantidad' => 570, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Ajo', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Yogur natural', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Cereal', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Queso bajo en grasa', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Manteca', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Café', 'cantidad' => 250, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Masa para empanadas', 'cantidad' => 280, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Yogur bebible', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Avena', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Leche', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Canela', 'cantidad' => 18, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Bife magro', 'cantidad' => 250, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Lechuga', 'cantidad' => 150, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Pechuga de pollo', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Crutones', 'cantidad' => 75, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Salsa césar', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Harina', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Dulce de leche', 'cantidad' => 370, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Coco rallado', 'cantidad' => 125, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Yerba Mate', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Galletas dulces', 'cantidad' => 450, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Galletas de arroz', 'cantidad' => 130, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Carne para asado', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Vegetales mixtos', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta de Casa', 'ingrediente' => 'Frutas congeladas', 'cantidad' => 300, 'unidad' => 'g'],

            // Proteica
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Ajo', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Arroz integral', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Pollo', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Carne molida de pavo', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Tortilla de maíz', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Lechuga', 'cantidad' => 150, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Tomate', 'cantidad' => 570, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Aguacate', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Pasta integral', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Atún enlatado', 'cantidad' => 312, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Vegetales mixtos', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Bife magro', 'cantidad' => 250, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Huevo', 'cantidad' => 720, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Garbanzos', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Cebolla', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Leche', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Proteína en polvo', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Filete de salmón', 'cantidad' => 350, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Limón', 'cantidad' => 440, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Brócoli', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Calabaza', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Yogur griego', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Almendras', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Avena', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Papa', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Queso cottage', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Mango', 'cantidad' => 530, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Manzana', 'cantidad' => 900, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Banana', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Semillas', 'cantidad' => 250, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Quinoa', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Tofu', 'cantidad' => 275, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Salsa de soja', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Nueces', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Pan integral', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Mantequilla de maní', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Pechuga de pollo', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Dátiles', 'cantidad' => 250, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Lentejas cocidas', 'cantidad' => 570, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Pescado', 'cantidad' => 350, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Puré de papas', 'cantidad' => 230, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Yogur proteico', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Cereal', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Jamón', 'cantidad' => 175, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Queso bajo en grasa', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Salsa de tomate', 'cantidad' => 250, 'unidad' => 'g'],
            ['canasta' => 'Canasta Proteica', 'ingrediente' => 'Hummus', 'cantidad' => 220, 'unidad' => 'g'],

            // Express
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Atún enlatado', 'cantidad' => 312, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Zanahoria', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Aguacate', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Tortilla de maíz', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Pan integral', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Pollo', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Lechuga', 'cantidad' => 150, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Tomate', 'cantidad' => 570, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Pechuga de pollo', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Lentejas cocidas', 'cantidad' => 570, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Arroz blanco', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Cebolla', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Huevo', 'cantidad' => 720, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Yogur natural', 'cantidad' => 750, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Granola', 'cantidad' => 275, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Barritas de cereal', 'cantidad' => 150, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Mantequilla de maní', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Mayonesa', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Perejil', 'cantidad' => 10, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Hamburguesas vegetarianas', 'cantidad' => 150, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Vegetales mixtos', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Mango', 'cantidad' => 530, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Manzana', 'cantidad' => 900, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Banana', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Naranja', 'cantidad' => 1200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Leche', 'cantidad' => 1000, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Queso bajo en grasa', 'cantidad' => 200, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Galletas integrales', 'cantidad' => 280, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Muffins', 'cantidad' => 300, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Café', 'cantidad' => 250, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Pasta', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Yogur bebible', 'cantidad' => 500, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Avena', 'cantidad' => 400, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Jamón', 'cantidad' => 175, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Sopa instantánea', 'cantidad' => 85, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Frutos secos variados', 'cantidad' => 130, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Gelatina light', 'cantidad' => 600, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Batata', 'cantidad' => 800, 'unidad' => 'g'],
            ['canasta' => 'Canasta Express', 'ingrediente' => 'Frutas congeladas', 'cantidad' => 300, 'unidad' => 'g'],
        ];

        foreach ($datos as $item) {
            $canasta = $canastas->get($item['canasta']);
            $ingrediente = $ingredientes->get($item['ingrediente']);

            if ($canasta && $ingrediente) {
                DB::table('canasta_ingrediente')->updateOrInsert(
                    [
                        'id_canasta' => $canasta->id_canasta,
                        'id_ingrediente' => $ingrediente->id_ingrediente
                    ],
                    [
                        'cantidad' => $item['cantidad'],
                        'unidad_base' => $item['unidad'],
                        'subtotal' => $ingrediente->precio_estimado,
                        'created_at' => now(),
                        'updated_at' => now()
                    ]
                );
            }
        }

        foreach ($canastas as $canasta) {
            $precioTotal = $canasta->ingredientes->sum(function ($ingrediente) {
                return $ingrediente->pivot->subtotal;
            });

            $canasta->update(['precio_total' => $precioTotal]);
        }
    }
}
