<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IngredienteSeeder extends Seeder
{

    public function run(): void
    {
        DB::table('ingredientes')->insert([
            // Avena
            [
                'nombre' => 'Avena',
                'calorias' => 389,
                'proteinas' => 16,
                'carbohidratos' => 66,
                'grasas' => 7,
                'precio_estimado' => 1.90,
                'descripcion' => 'La avena es una excelente fuente de fibra soluble, ideal para el desayuno.',
                'unidad' => 'g',
            ],
            // Leche 
            [
                'nombre' => 'Leche',
                'calorias' => 42,
                'proteinas' => 3.4,
                'carbohidratos' => 5,
                'grasas' => 1,
                'precio_estimado' => 0.97,
                'descripcion' => 'Leche natural o vegetal, fuente de calcio y proteínas.',
                'unidad' => 'g',
            ],
            // Banana
            [
                'nombre' => 'Banana',
                'calorias' => 89,
                'proteinas' => 1.1,
                'carbohidratos' => 23,
                'grasas' => 0.3,
                'precio_estimado' => 3.99,
                'descripcion' => 'Fruta tropical rica en potasio y fibra.',
                'unidad' => 'g',
            ],
            // Frutos rojos
            [
                'nombre' => 'Frutos rojos',
                'calorias' => 57,
                'proteinas' => 1,
                'carbohidratos' => 14,
                'grasas' => 0.3,
                'precio_estimado' => 1.83,
                'descripcion' => 'Berries como fresas, frambuesas y moras, ricos en antioxidantes.',
                'unidad' => 'g',
            ],
            // Pepino
            [
                'nombre' => 'Pepino',
                'calorias' => 16,
                'proteinas' => 0.7,
                'carbohidratos' => 3.6,
                'grasas' => 0.1,
                'precio_estimado' => 0.42,
                'descripcion' => 'Hortaliza refrescante, con alto contenido de agua.',
                'unidad' => 'g',
            ],
            // Tomate
            [
                'nombre' => 'Tomate',
                'calorias' => 18,
                'proteinas' => 0.9,
                'carbohidratos' => 3.9,
                'grasas' => 0.2,
                'precio_estimado' => 4.41,
                'descripcion' => 'Fruta rica en licopeno y vitamina C.',
                'unidad' => 'g',
            ],
            // Cebolla
            [
                'nombre' => 'Cebolla',
                'calorias' => 40,
                'proteinas' => 1.1,
                'carbohidratos' => 9.3,
                'grasas' => 0.1,
                'precio_estimado' => 1.50,
                'descripcion' => 'Verdura aromática que aporta sabor y es rica en antioxidantes.',
                'unidad' => 'g',
            ],
            // Aceitunas negras
            [
                'nombre' => 'Aceitunas negras',
                'calorias' => 115,
                'proteinas' => 0.8,
                'carbohidratos' => 6,
                'grasas' => 10,
                'precio_estimado' => 1.15,
                'descripcion' => 'Aceitunas curadas con un alto contenido de grasas saludables.',
                'unidad' => 'g',
            ],
            // Queso feta
            [
                'nombre' => 'Queso feta',
                'calorias' => 264,
                'proteinas' => 14.2,
                'carbohidratos' => 4.1,
                'grasas' => 21.2,
                'precio_estimado' => 2.39,
                'descripcion' => 'Queso fresco de sabor salado, originario de Grecia.',
                'unidad' => 'g',
            ],
            // Aceite de oliva
            [
                'nombre' => 'Aceite de oliva',
                'calorias' => 884,
                'proteinas' => 0,
                'carbohidratos' => 0,
                'grasas' => 100,
                'precio_estimado' => 4.45,
                'descripcion' => 'Aceite vegetal extraído de aceitunas, rico en grasas monoinsaturadas.',
                'unidad' => 'g',
            ],
            // Orégano
            [
                'nombre' => 'Orégano',
                'calorias' => 306,
                'proteinas' => 9,
                'carbohidratos' => 64,
                'grasas' => 10,
                'precio_estimado' => 0.65,
                'descripcion' => 'Especia aromática que se utiliza en la cocina mediterránea.',
                'unidad' => 'g',
            ],
            // Filete de salmón
            [
                'nombre' => 'Filete de salmón',
                'calorias' => 206,
                'proteinas' => 22,
                'carbohidratos' => 0,
                'grasas' => 12,
                'precio_estimado' => 8.03,
                'descripcion' => 'Pescado rico en ácidos grasos omega-3.',
                'unidad' => 'g',
            ],
            // Quinoa
            [
                'nombre' => 'Quinoa',
                'calorias' => 120,
                'proteinas' => 4.1,
                'carbohidratos' => 21.3,
                'grasas' => 1.9,
                'precio_estimado' => 2.73,
                'descripcion' => 'Cereal sin gluten, rico en proteínas y fibra.',
                'unidad' => 'g',
            ],
            // Ajo
            [
                'nombre' => 'Ajo',
                'calorias' => 149,
                'proteinas' => 6.4,
                'carbohidratos' => 33.1,
                'grasas' => 0.5,
                'precio_estimado' => 2.97,
                'descripcion' => 'Bulbo con propiedades medicinales y un fuerte sabor.',
                'unidad' => 'g',
            ],
            // Limón
            [
                'nombre' => 'Limón',
                'calorias' => 29,
                'proteinas' => 1.1,
                'carbohidratos' => 9.3,
                'grasas' => 0.3,
                'precio_estimado' => 1.06,
                'descripcion' => 'Fruta cítrica rica en vitamina C.',
                'unidad' => 'g',
            ],
            // Pasta integral
            [
                'nombre' => 'Pasta integral',
                'calorias' => 348,
                'proteinas' => 13,
                'carbohidratos' => 72,
                'grasas' => 2,
                'precio_estimado' => 1.21,
                'descripcion' => 'Pasta hecha de harina integral, rica en fibra.',
                'unidad' => 'g',
            ],
            // Zucchini
            [
                'nombre' => 'Zucchini',
                'calorias' => 17,
                'proteinas' => 1.2,
                'carbohidratos' => 3.1,
                'grasas' => 0.3,
                'precio_estimado' => 2.01,
                'descripcion' => 'Verdura baja en calorías, rica en agua.',
                'unidad' => 'g',
            ],
            // Pimientos
            [
                'nombre' => 'Pimientos',
                'calorias' => 20,
                'proteinas' => 0.9,
                'carbohidratos' => 4.7,
                'grasas' => 0.2,
                'precio_estimado' => 1.75,
                'descripcion' => 'Verdura rica en vitamina C y antioxidantes.',
                'unidad' => 'g',
            ],
            // Lentejas cocidas
            [
                'nombre' => 'Lentejas cocidas',
                'calorias' => 116,
                'proteinas' => 9,
                'carbohidratos' => 20,
                'grasas' => 0.4,
                'precio_estimado' => 0.79,
                'descripcion' => 'Legumbres ricas en proteína y fibra.',
                'unidad' => 'g',
            ],
            // Laurel
            [
                'nombre' => 'Laurel',
                'calorias' => 313,
                'proteinas' => 7.6,
                'carbohidratos' => 74.9,
                'grasas' => 8.4,
                'precio_estimado' => 0.85,
                'descripcion' => 'Hojas aromáticas utilizadas como especia.',
                'unidad' => 'g',
            ],
            // Papa
            [
                'nombre' => 'Papa',
                'calorias' => 77,
                'proteinas' => 2,
                'carbohidratos' => 17,
                'grasas' => 0.1,
                'precio_estimado' => 2.11,
                'descripcion' => 'Tubérculo rico en carbohidratos.',
                'unidad' => 'g',
            ],
            // Berenjena
            [
                'nombre' => 'Berenjena',
                'calorias' => 25,
                'proteinas' => 0.8,
                'carbohidratos' => 5.9,
                'grasas' => 0.2,
                'precio_estimado' => 1.39,
                'descripcion' => 'Verdura rica en fibra y baja en calorías.',
                'unidad' => 'g',
            ],
            // Pan integral
            [
                'nombre' => 'Pan integral',
                'calorias' => 247,
                'proteinas' => 8.5,
                'carbohidratos' => 41,
                'grasas' => 3.4,
                'precio_estimado' => 2.51,
                'descripcion' => 'Fuente de carbohidratos complejos, ideal para sándwiches saludables.',
                'unidad' => 'g',
            ],
            // Pollo
            [
                'nombre' => 'Pollo',
                'calorias' => 165,
                'proteinas' => 31,
                'carbohidratos' => 0,
                'grasas' => 3.6,
                'precio_estimado' => 4.38,
                'descripcion' => 'Carne blanca, rica en proteínas y baja en grasas, ideal para platos principales.',
                'unidad' => 'g',
            ],
            // Hummus
            [
                'nombre' => 'Hummus',
                'calorias' => 166,
                'proteinas' => 7.9,
                'carbohidratos' => 14.3,
                'grasas' => 9.6,
                'precio_estimado' => 1.79,
                'descripcion' => 'Pasta cremosa hecha a base de garbanzos, tahini, limón y ajo, rica en proteínas vegetales.',
                'unidad' => 'g',
            ],
            // Zanahoria
            [
                'nombre' => 'Zanahoria',
                'calorias' => 41,
                'proteinas' => 0.9,
                'carbohidratos' => 9.6,
                'grasas' => 0.2,
                'precio_estimado' => 0.90,
                'descripcion' => 'Hortaliza dulce y rica en betacarotenos, ideal para sopas y guisos.',
                'unidad' => 'g',
            ],
            // Garbanzos
            [
                'nombre' => 'Garbanzos',
                'calorias' => 164,
                'proteinas' => 8.9,
                'carbohidratos' => 27.4,
                'grasas' => 2.6,
                'precio_estimado' => 0.75,
                'descripcion' => 'Legumbre rica en proteínas y fibra, ideal para curry y sopas.',
                'unidad' => 'g',
            ],
            // Aguacate
            [
                'nombre' => 'Aguacate',
                'calorias' => 160,
                'proteinas' => 2,
                'carbohidratos' => 8.5,
                'grasas' => 14.7,
                'precio_estimado' => 3.20,
                'descripcion' => 'Fruta rica en grasas saludables y fibra.',
                'unidad' => 'g',
            ],
            // Huevo
            [
                'nombre' => 'Huevo',
                'calorias' => 143,
                'proteinas' => 13,
                'carbohidratos' => 1.1,
                'grasas' => 10,
                'precio_estimado' => 2.59,
                'descripcion' => 'Fuente completa de proteína, usado para empanar o como aglutinante.',
                'unidad' => 'g',
            ],
            // Arroz integral
            [
                'nombre' => 'Arroz integral',
                'calorias' => 111,
                'proteinas' => 2.6,
                'carbohidratos' => 23,
                'grasas' => 0.9,
                'precio_estimado' => 1.70,
                'descripcion' => 'Cereal integral rico en fibra, ideal para acompañar ensaladas y bowls.',
                'unidad' => 'g',
            ],
            // Yogur natural
            [
                'nombre' => 'Yogur natural',
                'calorias' => 59,
                'proteinas' => 3.5,
                'carbohidratos' => 4.7,
                'grasas' => 3.3,
                'precio_estimado' => 1.15,
                'descripcion' => 'Yogur sin azúcar, ideal para desayuno o merienda.',
                'unidad' => 'g',
            ],
            // Yogur griego
            [
                'nombre' => 'Yogur griego',
                'calorias' => 59,
                'proteinas' => 10,
                'carbohidratos' => 3.6,
                'grasas' => 0.4,
                'precio_estimado' => 1.50,
                'descripcion' => 'Yogur denso y cremoso, rico en proteínas.',
                'unidad' => 'g',
            ],
            // Miel
            [
                'nombre' => 'Miel',
                'calorias' => 304,
                'proteinas' => 0.3,
                'carbohidratos' => 82,
                'grasas' => 0,
                'precio_estimado' => 4.64,
                'descripcion' => 'Edulcorante natural proveniente de las abejas.',
                'unidad' => 'g',
            ],
            // Nueces
            [
                'nombre' => 'Nueces',
                'calorias' => 654,
                'proteinas' => 15,
                'carbohidratos' => 14,
                'grasas' => 65,
                'precio_estimado' => 2.65,
                'descripcion' => 'Frutos secos ricos en grasas saludables y antioxidantes.',
                'unidad' => 'g',
            ],
            // Manzana
            [
                'nombre' => 'Manzana',
                'calorias' => 52,
                'proteinas' => 0.3,
                'carbohidratos' => 14,
                'grasas' => 0.2,
                'precio_estimado' => 3.06,
                'descripcion' => 'Fruta crujiente y dulce, buena fuente de fibra.',
                'unidad' => 'g',
            ],
            // Almendras
            [
                'nombre' => 'Almendras',
                'calorias' => 579,
                'proteinas' => 21.2,
                'carbohidratos' => 21.6,
                'grasas' => 49.9,
                'precio_estimado' => 2.28,
                'descripcion' => 'Frutos secos ricos en grasas saludables.',
                'unidad' => 'g',
            ],
            // Chía
            [
                'nombre' => 'Chía',
                'calorias' => 486,
                'proteinas' => 16.5,
                'carbohidratos' => 42.1,
                'grasas' => 30.7,
                'precio_estimado' => 1.36,
                'descripcion' => 'Semillas pequeñas ricas en fibra, proteínas y grasas saludables.',
                'unidad' => 'g',
            ],
            // Queso bajo en grasa
            [
                'nombre' => 'Queso bajo en grasa',
                'calorias' => 150,
                'proteinas' => 10,
                'carbohidratos' => 2,
                'grasas' => 10,
                'precio_estimado' => 3.13,
                'descripcion' => 'Queso reducido en grasa, ideal para dietas saludables.',
                'unidad' => 'g',
            ],
            // Batata
            [
                'nombre' => 'Batata',
                'calorias' => 86,
                'proteinas' => 1.6,
                'carbohidratos' => 20.1,
                'grasas' => 0.1,
                'precio_estimado' => 3.27,
                'descripcion' => 'Tubérculo dulce y nutritivo, fuente de vitamina A.',
                'unidad' => 'g',
            ],
            // Pescado
            [
                'nombre' => 'Pescado',
                'calorias' => 200,
                'proteinas' => 20,
                'carbohidratos' => 0,
                'grasas' => 10,
                'precio_estimado' => 9.10,
                'descripcion' => 'Pescado fresco o congelado, fuente de proteínas y omega-3.',
                'unidad' => 'g',
            ],
            // Pan de centeno
            [
                'nombre' => 'Pan de centeno',
                'calorias' => 259,
                'proteinas' => 9.6,
                'carbohidratos' => 48.2,
                'grasas' => 3.3,
                'precio_estimado' => 2.48,
                'descripcion' => 'Pan hecho con harina de centeno, más denso y nutritivo que el pan blanco.',
                'unidad' => 'g',
            ],
            // Albahaca
            [
                'nombre' => 'Albahaca',
                'calorias' => 23,
                'proteinas' => 3.2,
                'carbohidratos' => 3.7,
                'grasas' => 0.6,
                'precio_estimado' => 1.54,
                'descripcion' => 'Hierba aromática usada en la cocina mediterránea, especialmente en pesto.',
                'unidad' => 'g',
            ],
            // Piñones
            [
                'nombre' => 'Piñones',
                'calorias' => 673,
                'proteinas' => 14,
                'carbohidratos' => 13.1,
                'grasas' => 68.4,
                'precio_estimado' => 5.88,
                'descripcion' => 'Semillas de pino comestibles, usadas en pesto y otros platillos mediterráneos.',
                'unidad' => 'g',
            ],
            // Queso parmesano
            [
                'nombre' => 'Queso parmesano',
                'calorias' => 431,
                'proteinas' => 38,
                'carbohidratos' => 4.1,
                'grasas' => 29.5,
                'precio_estimado' => 1.53,
                'descripcion' => 'Queso curado italiano con sabor fuerte y salado.',
                'unidad' => 'g',
            ],
            // Rúcula
            [
                'nombre' => 'Rúcula',
                'calorias' => 25,
                'proteinas' => 2.6,
                'carbohidratos' => 3.7,
                'grasas' => 0.7,
                'precio_estimado' => 1.57,
                'descripcion' => 'Hortaliza de hojas verdes con un sabor ligeramente picante, usada en ensaladas.',
                'unidad' => 'g',
            ],
            // Espinaca
            [
                'nombre' => 'Espinaca',
                'calorias' => 23,
                'proteinas' => 2.9,
                'carbohidratos' => 3.6,
                'grasas' => 0.4,
                'precio_estimado' => 1.24,
                'descripcion' => 'Hortaliza rica en hierro y vitaminas.',
                'unidad' => 'g',
            ],
            // Vegetales mixtos
            [
                'nombre' => 'Vegetales mixtos',
                'calorias' => 45,
                'proteinas' => 1.5,
                'carbohidratos' => 10,
                'grasas' => 0.3,
                'precio_estimado' => 1.97,
                'descripcion' => 'Mezcla de verduras variadas como zanahoria, arvejas y choclo.',
                'unidad' => 'g',
            ],
            // Naranja
            [
                'nombre' => 'Naranja',
                'calorias' => 47,
                'proteinas' => 0.9,
                'carbohidratos' => 11.8,
                'grasas' => 0.1,
                'precio_estimado' => 2.99,
                'descripcion' => 'Fruta cítrica jugosa y rica en vitamina C.',
                'unidad' => 'g',
            ],
            // Mango
            [
                'nombre' => 'Mango',
                'calorias' => 60,
                'proteinas' => 0.8,
                'carbohidratos' => 15,
                'grasas' => 0.4,
                'precio_estimado' => 1.62,
                'descripcion' => 'Fruta tropical jugosa y dulce, rica en vitamina C.',
                'unidad' => 'g',
            ],
            // Curry
            [
                'nombre' => 'Curry',
                'calorias' => 335,
                'proteinas' => 15,
                'carbohidratos' => 47,
                'grasas' => 12,
                'precio_estimado' => 3.15,
                'descripcion' => 'Especia aromática y picante, base para curry.',
                'unidad' => 'g',
            ],
            // Leche de coco
            [
                'nombre' => 'Leche de coco',
                'calorias' => 230,
                'proteinas' => 2.3,
                'carbohidratos' => 6.9,
                'grasas' => 24,
                'precio_estimado' => 3.38,
                'descripcion' => 'Leche vegetal, rica en grasas saludables, utilizada en platos del sudeste asiático.',
                'unidad' => 'g',
            ],
            // Tofu
            [
                'nombre' => 'Tofu',
                'calorias' => 76,
                'proteinas' => 8,
                'carbohidratos' => 1.9,
                'grasas' => 4.8,
                'precio_estimado' => 1.90,
                'descripcion' => 'Proteína vegetal hecha a partir de soja, ideal para salteados y ensaladas.',
                'unidad' => 'g',
            ],
            // Brócoli
            [
                'nombre' => 'Brócoli',
                'calorias' => 34,
                'proteinas' => 2.8,
                'carbohidratos' => 6.6,
                'grasas' => 0.4,
                'precio_estimado' => 0.77,
                'descripcion' => 'Verdura rica en vitamina C, fibra y antioxidantes.',
                'unidad' => 'g',
            ],
            // Frijoles negros
            [
                'nombre' => 'Frijoles negros',
                'calorias' => 339,
                'proteinas' => 21.6,
                'carbohidratos' => 62.4,
                'grasas' => 0.9,
                'precio_estimado' => 2.83,
                'descripcion' => 'Legumbre rica en proteínas, fibra y antioxidantes, ideal para preparar chili.',
                'unidad' => 'g',
            ],
            // Láminas de lasaña
            [
                'nombre' => 'Láminas de lasaña',
                'calorias' => 353,
                'proteinas' => 12,
                'carbohidratos' => 70,
                'grasas' => 1.5,
                'precio_estimado' => 5.01,
                'descripcion' => 'Pasta seca en forma de láminas, ideal para preparar lasañas. Puede ser sin huevo para versión vegana.',
                'unidad' => 'g',
            ],
            // Bechamel vegana
            [
                'nombre' => 'Bechamel vegana',
                'calorias' => 120,
                'proteinas' => 1.5,
                'carbohidratos' => 10,
                'grasas' => 8,
                'precio_estimado' => 2.87,
                'descripcion' => 'Salsa cremosa a base de bebida vegetal y harina, sin lácteos, perfecta para platos gratinados.',
                'unidad' => 'g',
            ],
            // Carne para milanesa
            [
                'nombre' => 'Carne para milanesa',
                'calorias' => 250,
                'proteinas' => 26,
                'carbohidratos' => 0,
                'grasas' => 17,
                'precio_estimado' => 8.50,
                'descripcion' => 'Carne vacuna cortada en filetes delgados, ideal para milanesas.',
                'unidad' => 'g',
            ],
            // Pan rallado
            [
                'nombre' => 'Pan rallado',
                'calorias' => 395,
                'proteinas' => 13,
                'carbohidratos' => 72,
                'grasas' => 5,
                'precio_estimado' => 0.86,
                'descripcion' => 'Pan seco molido, utilizado para empanar carnes y verduras.',
                'unidad' => 'g',
            ],
            // Carne picada
            [
                'nombre' => 'Carne picada',
                'calorias' => 250,
                'proteinas' => 20,
                'carbohidratos' => 0,
                'grasas' => 20,
                'precio_estimado' => 2.28,
                'descripcion' => 'Carne molida de res, ideal para guisos y hamburguesas.',
                'unidad' => 'g',
            ],
            // Puré de papas
            [
                'nombre' => 'Puré de papas',
                'calorias' => 110,
                'proteinas' => 2,
                'carbohidratos' => 20,
                'grasas' => 3,
                'precio_estimado' => 2.27,
                'descripcion' => 'Preparación cremosa a base de papas cocidas y pisadas.',
                'unidad' => 'g',
            ],
            // Masa para tarta
            [
                'nombre' => 'Masa para tarta',
                'calorias' => 402,
                'proteinas' => 4,
                'carbohidratos' => 48,
                'grasas' => 20,
                'precio_estimado' => 1.90,
                'descripcion' => 'Masa para preparar tartas o empanadas.',
                'unidad' => 'g',
            ],
            // Arroz blanco
            [
                'nombre' => 'Arroz blanco',
                'calorias' => 130,
                'proteinas' => 2.4,
                'carbohidratos' => 28,
                'grasas' => 0.3,
                'precio_estimado' => 1.40,
                'descripcion' => 'Cereal básico en muchas culturas, fuente de energía rápida.',
                'unidad' => 'g',
            ],
            // Carne molida de pavo
            [
                'nombre' => 'Carne molida de pavo',
                'calorias' => 150,
                'proteinas' => 22,
                'carbohidratos' => 0,
                'grasas' => 7,
                'precio_estimado' => 1.70,
                'descripcion' => 'Carne blanca molida, baja en grasas y rica en proteínas.',
                'unidad' => 'g',
            ],
            // Tortilla de maíz
            [
                'nombre' => 'Tortilla de maíz',
                'calorias' => 218,
                'proteinas' => 5.7,
                'carbohidratos' => 45,
                'grasas' => 2.8,
                'precio_estimado' => 2.22,
                'descripcion' => 'Base de los tacos, hecha a partir de maíz molido.',
                'unidad' => 'g',
            ],
            // Lechuga
            [
                'nombre' => 'Lechuga',
                'calorias' => 15,
                'proteinas' => 1.4,
                'carbohidratos' => 2.9,
                'grasas' => 0.2,
                'precio_estimado' => 1.59,
                'descripcion' => 'Verdura de hoja, ideal para ensaladas y rellenos frescos.',
                'unidad' => 'g',
            ],
            // Atún enlatado
            [
                'nombre' => 'Atún enlatado',
                'calorias' => 132,
                'proteinas' => 28,
                'carbohidratos' => 0,
                'grasas' => 1.5,
                'precio_estimado' => 6.68,
                'descripcion' => 'Pescado azul conservado, fuente rica en proteínas y omega 3.',
                'unidad' => 'g',
            ],
            // Bife magro
            [
                'nombre' => 'Bife magro',
                'calorias' => 190,
                'proteinas' => 28,
                'carbohidratos' => 0,
                'grasas' => 8,
                'precio_estimado' => 11.74,
                'descripcion' => 'Corte de carne vacuna con bajo contenido graso.',
                'unidad' => 'g',
            ],
            // Pechuga de pollo
            [
                'nombre' => 'Pechuga de pollo',
                'calorias' => 165,
                'proteinas' => 31,
                'carbohidratos' => 0,
                'grasas' => 3.6,
                'precio_estimado' => 2.83,
                'descripcion' => 'Carne magra alta en proteínas, ideal para grillar o usar en sándwiches.',
                'unidad' => 'g',
            ],
            // Pimentón
            [
                'nombre' => 'Pimentón',
                'calorias' => 282,
                'proteinas' => 14,
                'carbohidratos' => 58,
                'grasas' => 12,
                'precio_estimado' => 1.79,
                'descripcion' => 'Especia hecha de pimientos secos, ideal para guisos.',
                'unidad' => 'g',
            ],
            // Mermelada
            [
                'nombre' => 'Mermelada',
                'calorias' => 250,
                'proteinas' => 0,
                'carbohidratos' => 65,
                'grasas' => 0,
                'precio_estimado' => 1.84,
                'descripcion' => 'Preparado dulce de frutas cocidas con azúcar.',
                'unidad' => 'g',
            ],
            // Pasta
            [
                'nombre' => 'Pasta',
                'calorias' => 371,
                'proteinas' => 13,
                'carbohidratos' => 75,
                'grasas' => 1.5,
                'precio_estimado' => 0.80,
                'descripcion' => 'Fideos secos elaborados con harina de trigo.',
                'unidad' => 'g',
            ],
            // Cereal
            [
                'nombre' => 'Cereal',
                'calorias' => 379,
                'proteinas' => 7,
                'carbohidratos' => 85,
                'grasas' => 2,
                'precio_estimado' => 1.50,
                'descripcion' => 'Mezcla de granos ideal para el desayuno.',
                'unidad' => 'g',
            ],
            // Manteca
            [
                'nombre' => 'Manteca',
                'calorias' => 717,
                'proteinas' => 0.85,
                'carbohidratos' => 0.1,
                'grasas' => 81,
                'precio_estimado' => 2.30,
                'descripcion' => 'Grasa láctea usada para cocinar o untar.',
                'unidad' => 'g',
            ],
            // Café
            [
                'nombre' => 'Café',
                'calorias' => 1,
                'proteinas' => 0,
                'carbohidratos' => 0,
                'grasas' => 0,
                'precio_estimado' => 2.92,
                'descripcion' => 'Infusión estimulante obtenida de granos tostados.',
                'unidad' => 'g',
            ],
            // Masa para empanadas
            [
                'nombre' => 'Masa para empanadas',
                'calorias' => 280,
                'proteinas' => 6,
                'carbohidratos' => 35,
                'grasas' => 14,
                'precio_estimado' => 1.68,
                'descripcion' => 'Masa circular lista para rellenar y hornear/freír.',
                'unidad' => 'g',
            ],
            // Yogur bebible
            [
                'nombre' => 'Yogur bebible',
                'calorias' => 60,
                'proteinas' => 3,
                'carbohidratos' => 8,
                'grasas' => 1.5,
                'precio_estimado' => 1.88,
                'descripcion' => 'Yogur líquido, ideal para consumir rápidamente.',
                'unidad' => 'g',
            ],
            // Canela
            [
                'nombre' => 'Canela',
                'calorias' => 247,
                'proteinas' => 4,
                'carbohidratos' => 81,
                'grasas' => 1.2,
                'precio_estimado' => 1.36,
                'descripcion' => 'Especia aromática usada en platos dulces y bebidas.',
                'unidad' => 'g',
            ],
            // Crutones
            [
                'nombre' => 'Crutones',
                'calorias' => 407,
                'proteinas' => 12,
                'carbohidratos' => 50,
                'grasas' => 18,
                'precio_estimado' => 0.52,
                'descripcion' => 'Cubitos de pan tostado, ideales para ensaladas.',
                'unidad' => 'g',
            ],
            // Salsa césar
            [
                'nombre' => 'Salsa César',
                'calorias' => 320,
                'proteinas' => 2,
                'carbohidratos' => 3,
                'grasas' => 34,
                'precio_estimado' => 1.40,
                'descripcion' => 'Aderezo cremoso clásico para ensaladas.',
                'unidad' => 'g',
            ],
            // Harina
            [
                'nombre' => 'Harina',
                'calorias' => 364,
                'proteinas' => 10,
                'carbohidratos' => 76,
                'grasas' => 1,
                'precio_estimado' => 0.83,
                'descripcion' => 'Ingrediente básico para panes, pastas y postres.',
                'unidad' => 'g',
            ],
            // Dulce de leche
            [
                'nombre' => 'Dulce de leche',
                'calorias' => 315,
                'proteinas' => 5,
                'carbohidratos' => 50,
                'grasas' => 9,
                'precio_estimado' => 2.51,
                'descripcion' => 'Dulce espeso y tradicional de leche y azúcar.',
                'unidad' => 'g',
            ],
            // Coco rallado
            [
                'nombre' => 'Coco rallado',
                'calorias' => 660,
                'proteinas' => 7,
                'carbohidratos' => 24,
                'grasas' => 64,
                'precio_estimado' => 1.29,
                'descripcion' => 'Coco seco y rallado, usado en repostería.',
                'unidad' => 'g',
            ],
            // Yerba mate
            [
                'nombre' => 'Yerba mate',
                'calorias' => 0,
                'proteinas' => 0,
                'carbohidratos' => 0,
                'grasas' => 0,
                'precio_estimado' => 3.19,
                'descripcion' => 'Infusión tradicional de América del Sur.',
                'unidad' => 'g',
            ],
            // Galletas dulces
            [
                'nombre' => 'Galletas dulces',
                'calorias' => 450,
                'proteinas' => 5,
                'carbohidratos' => 70,
                'grasas' => 18,
                'precio_estimado' => 3.36,
                'descripcion' => 'Snacks dulces ideales para acompañar infusiones.',
                'unidad' => 'g',
            ],
            // Galletas de arroz
            [
                'nombre' => 'Galletas de arroz',
                'calorias' => 387,
                'proteinas' => 7,
                'carbohidratos' => 83,
                'grasas' => 3,
                'precio_estimado' => 1.45,
                'descripcion' => 'Snacks ligeros hechos a base de arroz inflado.',
                'unidad' => 'g',
            ],
            // Carne para asado
            [
                'nombre' => 'Carne para asado',
                'calorias' => 250,
                'proteinas' => 26,
                'carbohidratos' => 0,
                'grasas' => 17,
                'precio_estimado' => 6.84,
                'descripcion' => 'Cortes especiales de carne para parrilla.',
                'unidad' => 'g',
            ],
            // Frutas congeladas
            [
                'nombre' => 'Frutas congeladas',
                'calorias' => 50,
                'proteinas' => 0.5,
                'carbohidratos' => 12,
                'grasas' => 0.2,
                'precio_estimado' => 2.04,
                'descripcion' => 'Frutas seleccionadas y conservadas por congelación.',
                'unidad' => 'g',
            ],
            // Proteína en polvo
            [
                'nombre' => 'Proteína en polvo',
                'calorias' => 120,
                'proteinas' => 25,
                'carbohidratos' => 3,
                'grasas' => 1.5,
                'precio_estimado' => 17.28,
                'descripcion' => 'Suplemento proteico utilizado para aumentar la ingesta de proteínas.',
                'unidad' => 'g',
            ],
            // Calabaza
            [
                'nombre' => 'Calabaza',
                'calorias' => 26,
                'proteinas' => 1,
                'carbohidratos' => 7,
                'grasas' => 0,
                'precio_estimado' => 1.14,
                'descripcion' => 'Verdura baja en calorías, rica en vitamina A y fibra.',
                'unidad' => 'g',
            ],
            // Queso cottage
            [
                'nombre' => 'Queso cottage',
                'calorias' => 98,
                'proteinas' => 11,
                'carbohidratos' => 3,
                'grasas' => 4,
                'precio_estimado' => 1.26,
                'descripcion' => 'Queso fresco bajo en grasa, excelente fuente de proteína de alta calidad.',
                'unidad' => 'g',
            ],
            // Semillas
            [
                'nombre' => 'Semillas',
                'calorias' => 550,
                'proteinas' => 20,
                'carbohidratos' => 15,
                'grasas' => 45,
                'precio_estimado' => 2.28,
                'descripcion' => 'Mezcla de semillas como chía, sésamo y girasol, ricas en grasas buenas.',
                'unidad' => 'g',
            ],
            // Salsa de soja
            [
                'nombre' => 'Salsa de soja',
                'calorias' => 53,
                'proteinas' => 8,
                'carbohidratos' => 4.9,
                'grasas' => 0.6,
                'precio_estimado' => 2.50,
                'descripcion' => 'Condimento salado hecho a base de soja fermentada.',
                'unidad' => 'g',
            ],
            // Mantequilla de maní
            [
                'nombre' => 'Mantequilla de maní',
                'calorias' => 588,
                'proteinas' => 25,
                'carbohidratos' => 20,
                'grasas' => 50,
                'precio_estimado' => 2.85,
                'descripcion' => 'Pasta hecha de maní molido, rica en grasas saludables y proteínas.',
                'unidad' => 'g',
            ],
            // Dátiles
            [
                'nombre' => 'Dátiles',
                'calorias' => 282,
                'proteinas' => 2.5,
                'carbohidratos' => 75,
                'grasas' => 0.4,
                'precio_estimado' => 1.62,
                'descripcion' => 'Fruta deshidratada muy dulce y energética, rica en fibra y minerales.',
                'unidad' => 'g',
            ],
            // Yogur proteico
            [
                'nombre' => 'Yogur proteico',
                'calorias' => 60,
                'proteinas' => 10,
                'carbohidratos' => 3,
                'grasas' => 0,
                'precio_estimado' => 1.55,
                'descripcion' => 'Yogur alto en proteínas, ideal para dietas enfocadas en ganancia muscular o pérdida de grasa.',
                'unidad' => 'g',
            ],
            // Jamón
            [
                'nombre' => 'Jamón',
                'calorias' => 145,
                'proteinas' => 20,
                'carbohidratos' => 1,
                'grasas' => 6,
                'precio_estimado' => 3.41,
                'descripcion' => 'Producto cárnico curado, fuente de proteína de fácil acceso.',
                'unidad' => 'g',
            ],
            // Salsa de tomate
            [
                'nombre' => 'Salsa de tomate',
                'calorias' => 29,
                'proteinas' => 1,
                'carbohidratos' => 7,
                'grasas' => 0,
                'precio_estimado' => 4.90,
                'descripcion' => 'Salsa elaborada a base de tomates cocidos, ideal para pastas y guisos.',
                'unidad' => 'g',
            ],
            // Granola
            [
                'nombre' => 'Granola',
                'calorias' => 450,
                'proteinas' => 10,
                'carbohidratos' => 60,
                'grasas' => 20,
                'precio_estimado' => 3.49,
                'descripcion' => 'Mezcla de cereales, frutos secos y miel, ideal para desayunos o meriendas.',
                'unidad' => 'g',
            ],
            // Barritas de cereal
            [
                'nombre' => 'Barritas de cereal',
                'calorias' => 100,
                'proteinas' => 2,
                'carbohidratos' => 18,
                'grasas' => 3,
                'precio_estimado' => 2.05,
                'descripcion' => 'Barritas listas para consumir, hechas de cereales y frutas.',
                'unidad' => 'g',
            ],
            // Mayonesa
            [
                'nombre' => 'Mayonesa',
                'calorias' => 680,
                'proteinas' => 1,
                'carbohidratos' => 1,
                'grasas' => 75,
                'precio_estimado' => 2.04,
                'descripcion' => 'Aderezo cremoso ideal para sándwiches y ensaladas.',
                'unidad' => 'g',
            ],
            // Perejil
            [
                'nombre' => 'Perejil',
                'calorias' => 36,
                'proteinas' => 3,
                'carbohidratos' => 6,
                'grasas' => 1,
                'precio_estimado' => 0.50,
                'descripcion' => 'Hierba aromática que se usa fresca o seca para dar sabor.',
                'unidad' => 'g',
            ],
            // Hamburguesas vegetarianas
            [
                'nombre' => 'Hamburguesas vegetarianas',
                'calorias' => 200,
                'proteinas' => 10,
                'carbohidratos' => 20,
                'grasas' => 8,
                'precio_estimado' => 3.29,
                'descripcion' => 'Hamburguesas elaboradas con legumbres, verduras y cereales.',
                'unidad' => 'g',
            ],
            // Galletas integrales
            [
                'nombre' => 'Galletas integrales',
                'calorias' => 420,
                'proteinas' => 6,
                'carbohidratos' => 65,
                'grasas' => 15,
                'precio_estimado' => 1.59,
                'descripcion' => 'Galletas hechas con harina integral, ideales para colaciones saludables.',
                'unidad' => 'g',
            ],
            // Muffins
            [
                'nombre' => 'Muffins',
                'calorias' => 350,
                'proteinas' => 5,
                'carbohidratos' => 45,
                'grasas' => 15,
                'precio_estimado' => 3.43,
                'descripcion' => 'Pequeños bizcochos dulces ideales para desayunos o meriendas.',
                'unidad' => 'g',
            ],
            // Sopa instantánea
            [
                'nombre' => 'Sopa instantánea',
                'calorias' => 90,
                'proteinas' => 2,
                'carbohidratos' => 12,
                'grasas' => 3,
                'precio_estimado' => 0.65,
                'descripcion' => 'Sopa en sobre lista para preparar con agua caliente.',
                'unidad' => 'g',
            ],
            // Frutos secos variados
            [
                'nombre' => 'Frutos secos variados',
                'calorias' => 600,
                'proteinas' => 20,
                'carbohidratos' => 20,
                'grasas' => 50,
                'precio_estimado' => 3.59,
                'descripcion' => 'Mezcla energética de frutos secos como nueces, almendras y avellanas.',
                'unidad' => 'g',
            ],
            // Gelatina light
            [
                'nombre' => 'Gelatina light',
                'calorias' => 10,
                'proteinas' => 2,
                'carbohidratos' => 1,
                'grasas' => 0,
                'precio_estimado' => 1.11,
                'descripcion' => 'Postre liviano bajo en calorías, ideal para dietas.',
                'unidad' => 'g',
            ],
            // Harina integral
            [
                'nombre' => 'Harina integral',
                'calorias' => 340,
                'proteinas' => 13,
                'carbohidratos' => 72,
                'grasas' => 2.5,
                'precio_estimado' => 0.89,
                'descripcion' => 'Harina elaborada a partir del grano entero del trigo, rica en fibra.',
                'unidad' => 'g',
            ],
            // Yogur vegetal
            [
                'nombre' => 'Yogur vegetal',
                'calorias' => 80,
                'proteinas' => 3,
                'carbohidratos' => 12,
                'grasas' => 2,
                'precio_estimado' => 2.45,
                'descripcion' => 'Alternativa al yogur tradicional, hecho a base de plantas.',
                'unidad' => 'g',
            ],
            // Tahini
            [
                'nombre' => 'Tahini',
                'calorias' => 595,
                'proteinas' => 17,
                'carbohidratos' => 21,
                'grasas' => 54,
                'precio_estimado' => 2.95,
                'descripcion' => 'Pasta de semillas de sésamo, rica en grasas saludables.',
                'unidad' => 'g',
            ],
            // Chocolate amargo
            [
                'nombre' => 'Chocolate amargo',
                'calorias' => 546,
                'proteinas' => 5,
                'carbohidratos' => 46,
                'grasas' => 31,
                'precio_estimado' => 2.72,
                'descripcion' => 'Chocolate con alto porcentaje de cacao, fuente de antioxidantes y grasas saludables.',
                'unidad' => 'g',
            ],
        ]);
    }
}
